### ISSUE TITLE
include file not file

### ISSUE THREAD

**Issue by khaledgabr77** [mukmalone/AdpativeGoalManagement#4]
I try to build mir_robot but there is an error the include file that contains header files not found inside the mir_agm package
```
No such file or directory
 #include <mir_agm/WebComm.h>
```

**Comment by mukmalone** [comment]
Hi @khaledgabr77, I've had a similar issue on fresh installs.  

Try the following steps:
- In the `CMakeLists.txt` in the `mir_agm` directory comment out [these  lines](https://github.com/mukmalone/AdpativeGoalManagement/blob/913b335bbd43a0bfbaf1cd40482c1c988e3980f2/examples/mir_robot/mir_agm/CMakeLists.txt#L154-L161) 
- Run `catkin_make`
- If successful, uncomment the lines and run a `catkin_make` again

What I believe is happening is the complier first tries to compile the cpp files before building the msgs therefore they don't yet exist.  By commenting out the reference to the cpp files you allow the compiler to build the headers for the msgs.

Let me know how it goes.

**Comment by khaledgabr77** [comment]
Thanks, it's work fine now. 
I check the devel folder and found you are right it compile the CPP file without building header files.
